### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by LarchLiu** [LarchLiu/stargram#1]
- [ ] support github api
- [ ] sync starred repos to notion
- [ ] star and unstar with github
- [ ] support star list
- [ ] support bookmarks
- [ ] support twitter
